language: objective-c
osx_image: xcode7.2
script:
# - xctool -workspace 'GreedJSON.xcworkspace' -scheme Example -configuration Debug -sdk iphonesimulator clean build test ONLY_ACTIVE_ARCH=NO 
- set -o pipefail && xcodebuild clean build test -workspace GreedJSON.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint GreedJSON.podspec --verbose --use-libraries
